apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.backup.name }}
  namespace: {{ .Values.global.namespace.backup }}
  labels:
    {{- include "dbOperator.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.serviceAccount.backup.gcpServiceAccount }}"