apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRoleName }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["backup.csyeteam03.xyz"]
    resources: ["backupdatabaseschemas"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["backup.csyeteam03.xyz"]
    resources: ["backupdatabaseschemas/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]