creation_rules:
  - path_regex: .*enc\.yaml$
    gcp_kms: projects/csye7125-demo-project/locations/us-east1/keyRings/gke-key-ring13/cryptoKeys/sops-encryption-key
    encrypted_regex: "^(data|stringData|username|password|gsaEmail)$"