global:
  imagePullSecret: dockerhub-secret

apiServer:
  name: api-server
  replicas: 1
  image:
    repository: roarceus/api-server
    tag: latest
    pullPolicy: Always
  containerPort: 8080
  configMap:
    name: api-server-config
  envVars:
    OTLP_ENDPOINT: "jaeger-collector.istio-system:4317"
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  probes:
    liveness:
      path: /healthz
      initialDelay: 5
      period: 10
    readiness:
      path: /healthz
      initialDelay: 5
      period: 10
  flyway:
    image: roarceus/db-trace-processor
    tag: latest
    api:
      name: db-api-migration
      schema: api
      dbName: api
    trace:
      name: db-trace-migration
      schema: trace
      dbName: trace
      migrationPath: flyway/sql
    vector:
      name: db-vector-migration
      schema: vector
      dbName: vector
      migrationPath: flyway/sql
  gcs:
    bucketName: neu-trace-survey-bucket
  serviceAccount:
    name: api-server-sa
    gsaEmail: "api-server-gsa@csye7125-demo-project.iam.gserviceaccount.com"
  rbac:
    roleName: api-server-role
    roleBindingName: api-server-rolebinding
  hpa:
    name: api-server-hpa
    minReplicas: 1
    maxReplicas: 3
    cpuUtilization: 80
    memoryUtilization: 80
  pdb:
    name: api-server-pdb
    minAvailable: 1
  # Connection settings for Postgres
  postgres:
    host: "pg-postgresql.postgres.svc.cluster.local" # name-postgresql.namespace.svc.cluster.local tbc
    port: 5432
    dbName: "api"
    secretName: "postgres-secret"
    username: ""
    password: ""
  kafka:
    secretName: "kafka-secret"
    username: ""
    password: ""

# External Secrets Operator Config
externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStore:
    name: gcp-secret-store
    projectID: csye7125-demo-project
    clusterLocation: us-east4
    clusterName: gke-cluster-demo
  secrets:
    - name: postgres-username
      secretKey: username
    - name: postgres-password
      secretKey: password
    - name: kafka-username
      secretKey: username
    - name: kafka-password
      secretKey: password
