global:
  imagePullSecret: dockerhub-secret

apiServer:
  name: api-server
  replicas: 3
  image:
    repository: roarceus/api-server
    tag: latest
    pullPolicy: Always
  containerPort: 8080
  configMap:
    name: api-server-config
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 512Mi
  probes:
    liveness:
      path: /healthz
      initialDelay: 5
      period: 10
    readiness:
      path: /healthz
      initialDelay: 5
      period: 10
  flyway:
    image: roarceus/db-trace-processor
    tag: latest
    api:
      name: db-api-migration
      schema: api
      dbName: api
    trace:
      name: db-trace-migration
      schema: trace
      dbName: trace
      migrationPath: flyway/sql
  gcs:
    bucketName: neu-trace-survey-bucket
  serviceAccount:
    name: api-server-sa
    gsaEmail: "api-server-gsa@csye7125-demo-project.iam.gserviceaccount.com"
  # Connection settings for Postgres
  postgres:
    host: "pg-postgresql.postgres.svc.cluster.local" # name-postgresql.namespace.svc.cluster.local tbc
    port: 5432
    dbName: "api"
    secretName: "postgres-secret"
    username: ""
    password: ""

# External Secrets Operator Config
externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStore:
    name: gcp-secret-store
    projectID: csye7125-demo-project
    clusterLocation: us-east4
    clusterName: gke-cluster-demo
  secrets:
    - name: postgres-username
      secretKey: username
    - name: postgres-password
      secretKey: password
