apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.embeddingService.configMap.name }}
  namespace: {{ .Values.embeddingService.namespace }}
  labels:
    {{- include "embeddingService.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.embeddingService.postgres.host | quote }}
  DB_PORT: {{ .Values.embeddingService.postgres.port | quote }}
  DB_NAME: {{ .Values.embeddingService.postgres.name | quote }}
  DB_SCHEMA: {{ .Values.embeddingService.postgres.schema | quote }}