apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.embeddingService.rbac.roleBindingName }}
  namespace: {{ .Values.embeddingService.namespace }}
  labels:
    {{- include "embeddingService.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.embeddingService.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ .Values.embeddingService.rbac.roleName }}
  apiGroup: rbac.authorization.k8s.io