apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.embeddingService.serviceAccount.name }}
  namespace: {{ .Values.embeddingService.namespace }}
  labels:
    {{- include "embeddingService.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.embeddingService.serviceAccount.gsaEmail }}