apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: postgres-metrics
  namespace: postgres
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  endpoints:
  - port: 9187
    scheme: http
    interval: 30s
