apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.traceConsumer.configMap.name }}
  labels:
    {{- include "traceConsumer.labels" . | nindent 4 }}
data:
  KAFKA_BROKERS: {{ .Values.traceConsumer.kafka.brokers | quote }}
  KAFKA_TOPIC: {{ .Values.traceConsumer.kafka.topic | quote }}
  KAFKA_CONSUMER_GROUP: {{ .Values.traceConsumer.kafka.consumerGroup | quote }}
  KAFKA_AUTO_OFFSET_RESET: "earliest"
  KAFKA_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
  KAFKA_SASL_MECHANISM: "PLAIN"
  MAX_RETRIES: "{{ .Values.traceConsumer.processing.maxRetries }}"
  RETRY_BACKOFF_MS: "{{ .Values.traceConsumer.processing.retryBackoffMs }}"
  HEALTH_CHECK_INTERVAL: "{{ .Values.traceConsumer.processing.healthCheckInterval }}"
  DB_HOST: {{ .Values.traceConsumer.postgres.host | quote }}
  DB_PORT: {{ .Values.traceConsumer.postgres.port | quote }}
  DB_NAME: {{ .Values.traceConsumer.postgres.name | quote }}
  DB_SCHEMA: {{ .Values.traceConsumer.postgres.schema | quote }}