apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.traceConsumer.postgres.secretName }}
  namespace: trace-consumer
  labels:
    app: postgresql
type: Opaque
data:
  username: {{ .Values.traceConsumer.postgres.username | b64enc }}
  password: {{ .Values.traceConsumer.postgres.password | b64enc }}