apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.traceProcessor.configMap.name }}
  labels:
    {{- include "traceProcessor.labels" . | nindent 4 }}
data:
  KAFKA_BROKERS: {{ .Values.traceProcessor.kafka.brokers | quote }}
  KAFKA_INPUT_TOPIC: {{ .Values.traceProcessor.kafka.inputTopic | quote }}
  KAFKA_OUTPUT_TOPIC: {{ .Values.traceProcessor.kafka.outputTopic | quote }}
  KAFKA_CONSUMER_GROUP: {{ .Values.traceProcessor.kafka.consumerGroup | quote }}
  KAFKA_AUTO_OFFSET_RESET: "earliest"
  KAFKA_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
  KAFKA_SASL_MECHANISM: "PLAIN"
  MAX_CONCURRENT_JOBS: "5"
  PROCESSING_TIMEOUT: "300"
  MAX_RETRIES: "3"
  RETRY_BACKOFF_MS: "1000"
  GCS_BUCKET_NAME: {{ .Values.traceProcessor.gcs.bucketName | quote }}
  GSA_EMAIL: {{ .Values.traceProcessor.serviceAccount.gsaEmail | quote }}