apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.traceProcessor.kafka.secretName }}
  namespace: trace-processor
  labels:
    app: kafka
type: Opaque
data:
  username: {{ .Values.traceProcessor.kafka.username | b64enc }}
  password: {{ .Values.traceProcessor.kafka.password | b64enc }}