apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.traceProcessor.name }}
  labels:
    {{- include "traceProcessor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.traceProcessor.service.type }}
  ports:
    - port: {{ .Values.traceProcessor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "traceProcessor.selector" . | nindent 4 }}