apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.traceLlm.configMap.name }}
  labels:
    {{- include "traceLlm.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.traceLlm.postgres.host | quote }}
  DB_PORT: {{ .Values.traceLlm.postgres.port | quote }}
  DB_NAME: {{ .Values.traceLlm.postgres.name | quote }}
  DB_SCHEMA: {{ .Values.traceLlm.postgres.schema | quote }}