{{- if .Values.externalSecrets.enabled }}
# PostgreSQL credentials secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.traceLlm.postgres.secretName }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.traceLlm.postgres.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres-username
    - secretKey: password
      remoteRef:
        key: postgres-password
---
# Gemini API key secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.traceLlm.gemini.secretName }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.traceLlm.gemini.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: gemini-api-key
{{- end }}