apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.traceLlm.postgres.secretName }}
  namespace: trace-llm
  labels:
    app: postgresql
type: Opaque
data:
  username: {{ .Values.traceLlm.postgres.username | b64enc }}
  password: {{ .Values.traceLlm.postgres.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.traceLlm.gemini.secretName }}
  namespace: trace-llm
type: Opaque
data:
  api-key: {{ .Values.traceLlm.gemini.apiKey | b64enc }}