apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.traceLlm.service.name }}
  labels:
    {{- include "traceLlm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.traceLlm.service.type }}
  ports:
    - port: {{ .Values.traceLlm.service.port }}
      targetPort: {{ .Values.traceLlm.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "traceLlm.selector" . | nindent 4 }}