apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.traceLlm.serviceAccount.name }}
  labels:
    {{- include "traceLlm.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.traceLlm.serviceAccount.gsaEmail }}