apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apiServer.configMap.name }}
  labels:
    {{- include "apiServer.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.apiServer.postgres.host | quote }}
  DB_PORT: "{{ .Values.apiServer.postgres.port }}"
  DB_NAME: "{{ .Values.apiServer.postgres.dbName }}"
  DB_URL: "jdbc:postgresql://{{ .Values.apiServer.postgres.host }}:{{ .Values.apiServer.postgres.port }}/{{ .Values.apiServer.postgres.dbName }}"
  BUCKET_NAME: {{ .Values.apiServer.gcs.bucketName | quote }}
  GSA_EMAIL: {{ .Values.apiServer.serviceAccount.gsaEmail | quote }}
  OTLP_ENDPOINT: {{ .Values.apiServer.envVars.OTLP_ENDPOINT | quote }}
