{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.apiServer.postgres.secretName }}
  namespace: {{ .Values.apiServer.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.apiServer.postgres.secretName }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.secrets }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .name }}
  {{- end }}
{{- end }}
