{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.apiServer.postgres.secretName }}
  namespace: {{ .Values.apiServer.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.apiServer.postgres.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres-username
    - secretKey: password
      remoteRef:
        key: postgres-password
{{- end }}
---
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.apiServer.kafka.secretName }}
  namespace: {{ .Values.apiServer.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.apiServer.kafka.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: kafka-username
    - secretKey: password
      remoteRef:
        key: kafka-password
{{- end }}
