apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.apiServer.pdb.name }}
spec:
  minAvailable: {{ .Values.apiServer.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.apiServer.name }}
