apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiServer.postgres.secretName }}
  namespace: api-server
  labels:
    app: postgresql
type: Opaque
data:
  username: {{ .Values.apiServer.postgres.username | b64enc }}
  password: {{ .Values.apiServer.postgres.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiServer.kafka.secretName }}
  namespace: api-server
  labels:
    app: kafka
type: Opaque
data:
  username: {{ .Values.apiServer.kafka.username | b64enc }}
  password: {{ .Values.apiServer.kafka.password | b64enc }}