apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiServer.serviceAccount.name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.apiServer.serviceAccount.gsaEmail | quote }}
  labels:
    {{- include "apiServer.labels" . | nindent 4 }}
secrets:
  - name: {{ .Values.apiServer.serviceAccount.secretName }}