apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiServer.name }}-service
  labels:
    {{- include "apiServer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiServer.service.type }}
  selector:
    {{- include "apiServer.selector" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.apiServer.service.port }}
      targetPort: {{ .Values.apiServer.containerPort }}
